### ISSUE TITLE
Docker image could be a lot smaller

### ISSUE THREAD

**Issue by dheiman** [getzlab/slurm_gcp_docker#1]
Looking at the Dockerfile, you may inadvertently end up with a much larger image than intended - by having cleanup be its own step, you effectively do nothing but hide the files from the final image rather than actually remove them. See https://www.docker.com/blog/intro-guide-to-dockerfile-best-practices.

**Comment by julianhess** [comment]
This is addressed in the following lines

https://github.com/getzlab/slurm_gcp_docker/blob/67da00bb7721df6af074aa5c6192d31e3a90048b/src/Dockerfile#L78-L81

which copies over the contents of the finalized image, such that the actual image that gets burned to disk only contains a single squashed layer.

**Comment by julianhess** [comment]
BTW, I'm going to push much of this image to a container repo — it takes ~20 minutes to build Slurm.
