### ISSUE TITLE
Retry suspend script

### ISSUE THREAD

**Issue by Marlin-Na** [getzlab/slurm_gcp_docker#10]
Qing mentioned to me that she occasionally see some worker nodes not being deleted. I have also encountered this issue previously.

I suspect this is due to [gcloud compute instances delete](https://github.com/getzlab/slurm_gcp_docker/blob/master/src/slurm_suspend.sh#L14) may fail when there are too many nodes or called concurrently. I have seen such error in log even without preemption.

I think a simple solution is to retry the `gcloud` command. We can use
```
gcloud compute instances list --zones {zone} --quiet --format 'value(name)' --filter 'status=({RUNNING,TERMINATED})' # Ignore "STOPPING"
```
to obtain the running instances and compare it with what's in 
```
scontrol show hostnames <hostlist>
```
then delete the intersection. Retry several times until success.

**Comment by julianhess** [comment]
Yup, I've been noticing this bug too. This is new to me, so it seems like a change on Google's end has made the compute API less robust.

We'll probably have the bump the Slurm `SuspendTimeout`, since this may take a while.

**Comment by hurrialice** [comment]
I wonder if it is possible to print the names of worker VMs (and the number as well) that are still running upon exiting the workflow - just as a reminder for users to manually delete them if anything went wrong.

**Comment by julianhess** [comment]
That is a great idea. Added as a feature request to wolF.

**Comment by julianhess** [comment]
I'm still very jealous this is AWS-only: http://youtube.com/watch?v=_gDHeRB5Hfg

**Comment by julianhess** [comment]
BTW, it's funny that the gcloud API only fails when attempting to delete instances, but never add them. I wonder why that is … 🤔

**Comment by hurrialice** [comment]
(they will only _mistakenly_ make you pay more?

**Comment by julianhess** [comment]
"mistakenly"
